export const SAVE_CATALOG = "SAVE_CATALOG";
export const IS_ACTIVE = "IS_ACTIVE";
export const IS_PROMO = "IS_PROMO";
export const SAVE_PRODUCT_QUERY = "SAVE_PRODUCT_QUERY";
export const SAVE_SELECTED_PRODUCT = "SAVE_SELECTED_PRODUCT";
export const IS_FETCHING = "IS_FETCHING";